baseurl: "/website"
twitter_page_url: https://twitter.com/CactusSocietyIE
facebook_page_url: https://www.facebook.com/CactusandSucculentSocietyofIreland
facebook_group_url: https://www.facebook.com/groups/203262631112580/
society_contact_email: frankkeoghan2@gmail.com
society_contact_number: +35387 230 8330